os: osx
language: generic
sudo: required

matrix:
  include:
  - os: osx
    language: generic
    osx_image: xcode8.3
  - os: osx
    language: generic
    osx_image: xcode7.3


install:
- bash ./install.sh